name: Create-Environment-Variables
on:
  push: 
    branches: 
      - main
jobs:
  read-json-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      name: Creating Enviroment Variables
      with: 
        file-path: '.github/config/ci-config.json'
        level: '.dev'
        
    - name: "Checking Variables..."
      run: |
        echo Checking variables readfiles...